apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.muffinWallet.name }}
spec:
  type: {{ .Values.muffinWallet.service.type }}
  selector:
    app: {{ .Values.muffinWallet.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.muffinWallet.service.port }}
      targetPort: {{ .Values.muffinWallet.service.targetPort }}
---
{{- if .Values.muffinWallet.logService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.muffinWallet.name }}-log
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.muffinWallet.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.muffinWallet.logService.port }}
      targetPort: {{ .Values.muffinWallet.logService.targetPort }}
{{- end }}