apiVersion: v1
kind: Service
metadata:
  name: {{ include "muffin-currency.name" . }}
  labels:
    {{- include "muffin-currency.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "muffin-currency.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.ports.servicePort }}
      targetPort: {{ .Values.ports.containerPort }}
  type: {{ .Values.serviceType }}
