apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-muffin-wallet.fullname" . }}-env
  labels:
    {{- include "helm-muffin-wallet.labels" . | nindent 4 }}
data:
  JDK_JAVA_OPTIONS: -Dspring.config.additional-location=/app/config/application.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-muffin-wallet.fullname" . }}
  labels:
    {{- include "helm-muffin-wallet.labels" . | nindent 4 }}
data:
  application.yaml: |
    ---
    server:
      port: {{ .Values.config.server.port }}

    spring:
      datasource:
        url: {{ .Values.config.spring.datasource.url }}
        username: {{ .Values.config.spring.datasource.username }}

    currency:
      service:
        url: {{ .Values.config.currency.service.url }}
    management:
      endpoints:
        web:
          exposure:
            include: {{ .Values.config.management.endpoints.web.exposure.include }}
      endpoint:
        health:
          probes:
            enabled: {{ .Values.config.management.endpoint.health.probes.enabled }}
          show-details: {{ .Values.config.management.endpoint.health.showDetails }}

